services:
  db:
    image: postgres:16
    container_name: contacts_db
    environment:
      POSTGRES_DB: contacts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - contacts_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d contacts"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  contacts_pg_data:
